extends Node

# The keys can be integers or strings. As read from objects.cfg's AnimationID field.
var sprite_id = {
046 : preload("res://dk_images/furniture/torture_machine_tp/r1frame01.png"),
098 : preload("res://dk_images/furniture/workshop_machine_tp/AnimWorkshopMachine.tres"),
100 : preload("res://dk_images/furniture/flagpole_empty_tp/r1frame01.png"),
102 : preload("res://dk_images/furniture/flagpole_redflag_tp/AnimFlagpoleRed.tres"),
104 : preload("res://dk_images/furniture/flagpole_blueflag_tp/AnimFlagpoleBlue.tres"),
106 : preload("res://dk_images/furniture/flagpole_greenflag_tp/AnimFlagpoleGreen.tres"),
108 : preload("res://dk_images/furniture/flagpole_yellowflag_tp/AnimFlagpoleYellow.tres"),
114 : preload("res://dk_images/traps_doors/anim0116/AnimBox.tres"),
124 : preload("res://edited_images/lair/creature_generic/anim0126/AnimLairGeneric.tres"),
126 : preload("res://edited_images/lair/creature_orc/anim0128/r1frame01.png"),
128 : preload("res://edited_images/lair/creature_tentacle/anim0130/r1frame01.png"),
130 : preload("res://dk_images/furniture/scavenge_eye_tp/AnimScavengerEye.tres"),
132 : preload("res://edited_images/lair/creature_ghost/anim0134/r1frame01.png"),
134 : preload("res://edited_images/lair/creature_hound/anim0136/r1frame01.png"),
136 : preload("res://edited_images/lair/creature_spider/anim0138/AnimLairSpider.tres"),
138 : preload("res://edited_images/lair/creature_vampire/anim0140/r1frame01.png"),
140 : preload("res://edited_images/lair/creature_bug/anim0142/AnimLairBeetle.tres"),
142 : preload("res://edited_images/lair/creature_biledemon/anim0144/AnimLairBileDemon.tres"),
144 : preload("res://edited_images/lair/creature_warlock/anim0146/AnimLairWarlock.tres"),
146 : preload("res://edited_images/lair/creature_dkmistress/anim0148/AnimLairMistress.tres"),
148 : preload("res://edited_images/lair/creature_fly/anim0150/AnimLairFly.tres"),
150 : preload("res://edited_images/lair/creature_demonspawn/lairempty_tp/r1frame01.png"),
152 : preload("res://edited_images/lair/creature_dragon/anim0154/AnimLairDragon.tres"),
154 : preload("res://edited_images/lair/creature_generic/anim0156/r1frame01.png"),
156 : preload("res://edited_images/lair/creature_skeleton/anim0158/AnimLairSkeleton.tres"),
158 : preload("res://edited_images/lair/creature_horny/anim0160/AnimLairHornedReaper.tres"),
776 : preload("res://dk_images/crucials/anim0780/AnimHeroGate.tres"),
777 : preload("res://edited_images/icon_handofevil.png"),
781 : preload("res://dk_images/power_hand/anim0782/AnimePowerHandGold.tres"),
782 : preload("res://dk_images/power_hand/anim0783/AnimePowerHand.tres"),
783 : preload("res://dk_images/power_hand/anim0784/AnimePowerHandGrab.tres"),
785 : preload("res://dk_images/power_hand/anim0786/AnimePowerHandWhip.tres"),
789 : preload("res://dk_images/furniture/workshop_anvil_tp/r1frame01.png"),
791 : preload("res://dk_images/furniture/anim0791/r1frame01.png"),
793 : preload("res://dk_images/furniture/tombstone_tp/r1frame01.png"),
795 : preload("res://dk_images/furniture/training_machine_tp/AnimTrainingMachine.tres"),
796 : preload("res://dk_images/other/anim0797/r1frame01.png"),
797 : preload("res://dk_images/magic_fogs/anim0798/AnimTempleSpangle.tres"),
798 : preload("res://dk_images/magic_fogs/anim0801/AnimRedHeartFlame.tres"),
799 : preload("res://dk_images/magic_fogs/anim0802/AnimBlueHeartFlame.tres"),
800 : preload("res://dk_images/magic_fogs/anim0800/AnimGreenHeartFlame.tres"),
801 : preload("res://dk_images/magic_fogs/anim0799/AnimYellowHeartFlame.tres"),
804 : preload("res://dk_images/potions/anim0804/r1frame01.png"),
806 : preload("res://dk_images/potions/anim0806/r1frame01.png"),
808 : preload("res://dk_images/potions/anim0808/r1frame01.png"),
810 : preload("res://dk_images/traps_doors/anim0811/AnimSpinningKey.tres"),
818 : preload("res://dk_images/traps_doors/anim0811/AnimSpinningKey.tres"),
819 : preload("res://dk_images/food/anim0822/AnimChicken.tres"),
892 : preload("res://dk_images/furniture/anim0892/AnimSpike.tres"),
893 : preload("res://dk_images/food/anim0898/AnimEggGrowing1.tres"),
894 : preload("res://dk_images/food/anim0899/r1frame01.png"),
895 : preload("res://dk_images/food/anim0900/AnimEggWobbling3.tres"),
896 : preload("res://dk_images/food/anim0901/AnimEggCracking4.tres"),
901 : preload("res://dk_images/trapdoor_64/bonus_box_std.png"),
905 : preload("res://dk_images/statues/anim0907/r1frame01.png"),
930 : preload("res://dk_images/other/anim0932/r1frame01.png"),
934 : preload("res://dk_images/valuables/gold_pot_tp/AnimGoldPot.tres"),
936 : preload("res://dk_images/valuables/gold_hoard1_tp/AnimGoldHoard1.tres"),
937 : preload("res://dk_images/valuables/gold_hoard2_tp/AnimGoldHoard2.tres"),
938 : preload("res://dk_images/valuables/gold_hoard3_tp/AnimGoldHoard3.tres"),
939 : preload("res://dk_images/valuables/gold_hoard4_tp/AnimGoldHoard4.tres"),
940 : preload("res://dk_images/valuables/gold_hoard5_tp/AnimGoldHoard5.tres"),
948 : preload("res://dk_images/crucials/anim0950/AnimDungeonHeart.tres"),
950 : preload("res://dk_images/statues/anim0952/AnimLitStatue.tres"),
952 : preload("res://dk_images/statues/anim0954/r1frame01.png"),
958 : preload("res://dk_images/statues/anim0960/r1frame01.png"),
962 : preload("res://dk_images/other/anim0963/r1frame01.png"),
"BANNER" : preload("res://used_images/banner.png"),
"DRUID_LAIR" : preload("res://used_images/lair_druid.png"),
"FERN" : preload("res://used_images/fern.png"),
"FERN_BROWN" : preload("res://used_images/fern_brown.png"),
"FERN_SMALL" : preload("res://used_images/fern_small.png"),
"FERN_SMALL_BROWN" : preload("res://used_images/fern_small_brown.png"),
"FLAGPOLE_BLACKFLAG" : "",
"FLAGPOLE_ORANGEFLAG" : "",
"FLAGPOLE_PURPLEFLAG" : "",
"FLAGPOLE_WHITEFLAG" : "",
"GOLDEN_ARMOR" : preload("res://dk_images/statues/anim0956/r1frame01.png"),
"HEARTFLAME_BLACK" : "",
"HEARTFLAME_ORANGE" : "",
"HEARTFLAME_PURPLE" : "",
"HEARTFLAME_WHITE" : "",
"ICE_PILLAR" : preload("res://used_images/ice_pillar.png"),
"ICE_PILLAR_SMALL" : preload("res://used_images/ice_rock.png"),
"JUNGLE_CATTAILS" : preload("res://used_images/cattails.png"),
"JUNGLE_LILYPAD" : preload("res://used_images/lilypad.png"),
"KNIGHTSTATUE" : preload("res://dk_images/statues/anim0958/r1frame01.png"),
"LANTERNPOST_STAND" : preload("res://used_images/lantern_pst.png"),
"LAVA_PILLAR" : preload("res://used_images/lava_pillar.png"),
"LAVA_PILLAR_SMALL" : preload("res://used_images/lava_rock.png"),
"MUSHROOM_GREEN_LUM" : preload("res://used_images/mushroom_green.png"),
"MUSHROOM_RED_LUM" : preload("res://used_images/mushroom_red.png"),
"MUSHROOM_YELLOW_LUM" : preload("res://used_images/mushroom_yellow.png"),
"POTION_BROWN" : preload("res://used_images/potion_brown.png"),
"POTION_RED" : preload("res://used_images/potion_red.png"),
"POTION_WHITE" : preload("res://used_images/potion_white.png"),
"POTION_YELLOW" : preload("res://used_images/potion_yellow.png"),

"ROCK_PILLAR" : preload("res://used_images/rock_pillar.png"),
"ROCK_PILLAR_SMALL" : preload("res://used_images/rock.png"),
"IMG_ARMAGEDDON" : preload("res://dk_images/keepower_64/armagedn_std.png"),
"IMG_POSSESS_CREATURE" : preload("res://dk_images/keepower_64/possess_std.png"),
"IMG_HAND_OF_EVIL" : preload("res://edited_images/icon_handofevil.png"),
"IMG_CREATE_IMP" : preload("res://dk_images/keepower_64/imp_std.png"),
"IMG_MUST_OBEY" : preload("res://edited_images/mustobey.png"),
"IMG_SLAP" : preload("res://edited_images/icon_slap.png"),
"IMG_SIGHT_OF_EVIL" : preload("res://dk_images/keepower_64/sight_std.png"),
"IMG_CALL_TO_ARMS" : preload("res://dk_images/keepower_64/cta_std.png"),
"IMG_CAVE_IN" : preload("res://dk_images/keepower_64/cavein_std.png"),
"IMG_HEAL_CREATURE" : preload("res://dk_images/keepower_64/heal_std.png"),
"IMG_HOLD_AUDIENCE" : preload("res://dk_images/keepower_64/holdaud_std.png"),
"IMG_LIGHTNING" : preload("res://dk_images/keepower_64/lightng_std.png"),
"IMG_SPEED_CREATURE" : preload("res://dk_images/keepower_64/speed_std.png"),
"IMG_PROTECT_CREATURE" : preload("res://dk_images/keepower_64/armor_std.png"),
"IMG_CONCEAL_CREATURE" : preload("res://dk_images/keepower_64/conceal_std.png"),
"IMG_DISEASE" : preload("res://dk_images/keepower_64/disease_std.png"),
"IMG_CHICKEN" : preload("res://dk_images/keepower_64/chicken_std.png"),
"IMG_DESTROY_WALLS" : preload("res://dk_images/keepower_64/dstwall_std.png"),
"IMG_TIME_BOMB" : preload("res://edited_images/timebomb.png"),
"IMG_POWER_SIGHT" : preload("res://dk_images/magic_fogs/anim0854/AnimCastedSight.tres"),

"IMG_WIZARD"    : preload("res://edited_images/creatr_icon_64/wizrd_std.png"),
"IMG_WIZARD_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_wizrd.png"),
"IMG_BARBARIAN" : preload("res://edited_images/creatr_icon_64/barbr_std.png"),
"IMG_BARBARIAN_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_barbr.png"),
"IMG_ARCHER"    : preload("res://edited_images/creatr_icon_64/archr_std.png"),
"IMG_ARCHER_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_archr.png"),
"IMG_MONK"      : preload("res://edited_images/creatr_icon_64/monk_std.png"),
"IMG_MONK_PORTRAIT"      :preload("res://dk_images/creature_portrait_64/creatr_portrt_monk.png"),
"IMG_DWARFA"    : preload("res://edited_images/creatr_icon_64/dwarf_std.png"),
"IMG_DWARFA_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_dwrf1.png"),
"IMG_KNIGHT"    : preload("res://edited_images/creatr_icon_64/knght_std.png"),
"IMG_KNIGHT_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_knigh.png"),
"IMG_AVATAR"    : preload("res://edited_images/creatr_icon_64/avatr_std.png"),
"IMG_AVATAR_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_avatr.png"),
"IMG_TUNNELLER" : preload("res://edited_images/creatr_icon_64/tunlr_std.png"),
"IMG_TUNNELLER_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_dwrf2.png"),
"IMG_WITCH"     : preload("res://edited_images/creatr_icon_64/prsts_std.png"),
"IMG_WITCH_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_witch.png"),
"IMG_GIANT"     : preload("res://edited_images/creatr_icon_64/giant_std.png"),
"IMG_GIANT_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_giant.png"),
"IMG_FAIRY"     : preload("res://edited_images/creatr_icon_64/fairy_std.png"),
"IMG_FAIRY_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_fairy.png"),
"IMG_THIEF"     : preload("res://edited_images/creatr_icon_64/thief_std.png"),
"IMG_THIEF_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_thief.png"),
"IMG_SAMURAI"   : preload("res://edited_images/creatr_icon_64/samur_std.png"),
"IMG_SAMURAI_PORTRAIT"   :preload("res://dk_images/creature_portrait_64/creatr_portrt_samur.png"),
"IMG_HORNY"     : preload("res://edited_images/creatr_icon_64/hornd_std.png"),
"IMG_HORNY_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_horny.png"),
"IMG_SKELETON"  : preload("res://edited_images/creatr_icon_64/skelt_std.png"),
"IMG_SKELETON_PORTRAIT"  :preload("res://dk_images/creature_portrait_64/creatr_portrt_skelt.png"),
"IMG_TROLL"     : preload("res://edited_images/creatr_icon_64/troll_std.png"),
"IMG_TROLL_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_troll.png"),
"IMG_DRAGON"    : preload("res://edited_images/creatr_icon_64/dragn_std.png"),
"IMG_DRAGON_PORTRAIT"    :preload("res://dk_images/creature_portrait_64/creatr_portrt_dragn.png"),
"IMG_DEMONSPAWN" : preload("res://edited_images/creatr_icon_64/dspwn_std.png"),
"IMG_DEMONSPAWN_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_spawn.png"),
"IMG_FLY"       : preload("res://edited_images/creatr_icon_64/fly_std.png"),
"IMG_FLY_PORTRAIT"       :preload("res://dk_images/creature_portrait_64/creatr_portrt_fly.png"),
"IMG_DARK_MISTRESS" : preload("res://edited_images/creatr_icon_64/dkmis_std.png"),
"IMG_DARK_MISTRESS_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_mistr.png"),
"IMG_SORCEROR"     : preload("res://edited_images/creatr_icon_64/warlk_std.png"),
"IMG_SORCEROR_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_warlk.png"),
"IMG_BILE_DEMON" : preload("res://edited_images/creatr_icon_64/biled_std.png"),
"IMG_BILE_DEMON_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_biled.png"),
"IMG_IMP"       : preload("res://edited_images/creatr_icon_64/imp_std.png"),
"IMG_IMP_PORTRAIT"       :preload("res://dk_images/creature_portrait_64/creatr_portrt_imp.png"),
"IMG_BUG"       : preload("res://edited_images/creatr_icon_64/bug_std.png"),
"IMG_BUG_PORTRAIT"       :preload("res://dk_images/creature_portrait_64/creatr_portrt_bug.png"),
"IMG_VAMPIRE"   : preload("res://edited_images/creatr_icon_64/vampr_std.png"),
"IMG_VAMPIRE_PORTRAIT"   :preload("res://dk_images/creature_portrait_64/creatr_portrt_vampr.png"),
"IMG_SPIDER"     : preload("res://edited_images/creatr_icon_64/spidr_std.png"),
"IMG_SPIDER_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_spidr.png"),
"IMG_HELL_HOUND" : preload("res://edited_images/creatr_icon_64/hound_std.png"),
"IMG_HELL_HOUND_PORTRAIT" :preload("res://dk_images/creature_portrait_64/creatr_portrt_hound.png"),
"IMG_GHOST"     : preload("res://edited_images/creatr_icon_64/ghost_std.png"),
"IMG_GHOST_PORTRAIT"     :preload("res://dk_images/creature_portrait_64/creatr_portrt_ghost.png"),
"IMG_TENTACLE"  : preload("res://edited_images/creatr_icon_64/tentc_std.png"),
"IMG_TENTACLE_PORTRAIT"  :preload("res://dk_images/creature_portrait_64/creatr_portrt_tentc.png"),
"IMG_ORC"          : preload("res://edited_images/creatr_icon_64/orc_std.png"),
"IMG_ORC_PORTRAIT"          :preload("res://dk_images/creature_portrait_64/creatr_portrt_orc.png"),
"IMG_FLOATING_SPIRIT" : preload("res://dk_images/magic_dust/anim0981/r1frame02.png"),
"IMG_FLOATING_SPIRIT_PORTRAIT" :preload("res://dk_images/magic_dust/anim0981/r1frame02.png"),

"IMG_EFFECTGENERATOR_LAVA" : preload("res://edited_images/GUIEDIT-1/PIC27.png"),
"IMG_EFFECTGENERATOR_DRIPPING_WATER" : preload("res://edited_images/GUIEDIT-1/PIC28.png"),
"IMG_EFFECTGENERATOR_ROCK_FALL" : preload("res://edited_images/GUIEDIT-1/PIC29.png"),
"IMG_EFFECTGENERATOR_ENTRANCE_ICE" : preload("res://edited_images/GUIEDIT-1/PIC30.png"),
"IMG_EFFECTGENERATOR_DRY_ICE" : preload("res://edited_images/GUIEDIT-1/PIC31.png"),

"IMG_BOULDER" : preload("res://dk_images/trapdoor_64/trap_boulder_std.png"),
"IMG_ALARM" : preload("res://dk_images/trapdoor_64/trap_alarm_std.png"),
"IMG_POISON_GAS" : preload("res://dk_images/trapdoor_64/trap_gas_std.png"),
"IMG_LIGHTNING_TRAP" : preload("res://dk_images/trapdoor_64/trap_lightning_std.png"),
"IMG_WORD_OF_POWER" : preload("res://dk_images/trapdoor_64/trap_wop_std.png"),
"IMG_LAVA" : preload("res://dk_images/trapdoor_64/trap_lava_std.png"),
"IMG_TNT" : preload("res://used_images/tnt.png"),

"IMG_WOOD" : preload("res://dk_images/trapdoor_64/door_pers_wood_std.png"),
"IMG_BRACED" : preload("res://dk_images/trapdoor_64/door_pers_braced_std.png"),
"IMG_STEEL" : preload("res://dk_images/trapdoor_64/door_pers_iron_std.png"),
"IMG_MAGIC" : preload("res://dk_images/trapdoor_64/door_pers_magic_std.png"),

"IMG_ACTIONPOINT" : preload("res://Art/ActionPoint.png"),
"IMG_LIGHT" : preload("res://edited_images/GUIEDIT-1/PIC26.png"),
"IMG_BOOK_ICON" : preload("res://edited_images/icon_book.png"),

}
