extends Node

enum TYPE {
	NONE = 0
	OBJECT = 1
	SHOT = 2
	EFFECTELEM = 3
	DEADCREATURE = 4
	CREATURE = 5
	EFFECT = 6
	EFFECTGEN = 7
	TRAP = 8
	DOOR = 9
	UNKN10 = 10
	UNKN11 = 11
	AMBIENTSND = 12
	CAVEIN = 13
	EXTRA = 696969
}

const things = {
	TYPE.EXTRA : {
		"ACTIONPOINT" : "Action Point",
		"LIGHT" : "Light",
	},
	TYPE.DOOR : {
		"WOOD" : "Wooden Door",
		"BRACED" : "Braced Door",
		"STEEL" : "Iron Door",
		"MAGIC" : "Magic Door",
		"SECRET" : "Secret Door",
		"MIDAS" : "Midas Door",
	},
	TYPE.TRAP : {
		"BOULDER" : "Boulder Trap",
		"ALARM" : "Alarm Trap",
		"POISON_GAS" : "Poison Gas Trap",
		"LIGHTNING" : "Lightning Trap",
		"WORD_OF_POWER" : "Word of Power Trap",
		"LAVA" : "Lava Trap",
		"TNT" : "Demolition Trap",
		"DUMMYTRAP3" : "Dummy Trap 3",
		"DUMMYTRAP4" : "Dummy Trap 4",
		"DUMMYTRAP5" : "Dummy Trap 5",
		"DUMMYTRAP6" : "Dummy Trap 6",
		"DUMMYTRAP7" : "Dummy Trap 7",
	},
	TYPE.EFFECTGEN : {
		"EFFECTGENERATOR_LAVA" : "Lava Effect",
		"EFFECTGENERATOR_DRIPPING_WATER" : "Dripping Water Effect",
		"EFFECTGENERATOR_ROCK_FALL" : "Rock Fall Effect",
		"EFFECTGENERATOR_ENTRANCE_ICE" : "Entrance Ice Effect",
		"EFFECTGENERATOR_DRY_ICE" : "Dry Ice Effect",
	},
	TYPE.CREATURE : {
		"WIZARD" : "Wizard",
		"BARBARIAN" : "Barbarian",
		"ARCHER" : "Archer",
		"MONK" : "Monk",
		"DWARFA" : "Dwarf",
		"KNIGHT" : "Knight",
		"AVATAR" : "Avatar",
		"TUNNELLER" : "Tunneller",
		"WITCH" : "Witch",
		"GIANT" : "Giant",
		"FAIRY" : "Fairy",
		"THIEF" : "Thief",
		"SAMURAI" : "Samurai",
		"HORNY" : "Horned Reaper",
		"SKELETON" : "Skeleton",
		"TROLL" : "Troll",
		"DRAGON" : "Dragon",
		"DEMONSPAWN" : "Demon Spawn",
		"FLY" : "Fly",
		"DARK_MISTRESS" : "Dark Mistress",
		"SORCEROR" : "Warlock",
		"BILE_DEMON" : "Bile Demon",
		"IMP" : "Imp",
		"BUG" : "Beetle",
		"VAMPIRE" : "Vampire",
		"SPIDER" : "Spider",
		"HELL_HOUND" : "Hell Hound",
		"GHOST" : "Ghost",
		"TENTACLE" : "Tentacle",
		"ORC" : "Orc",
		"FLOATING_SPIRIT" : "Floating Spirit",
		"TIME_MAGE" : "Time Mage",
		"DRUID" : "Druid",
	},
	TYPE.OBJECT : {
		"BARREL" : "Barrel",
		"TORCH" : "Torch",
		"GOLD_CHEST" : "Gold Pot (500)",
		"TEMPLE_STATUE" : "Lit Statue",
		"SOUL_CONTAINER" : "Dungeon Heart",
		"GOLD" : "Gold Pot (250)",
		"TORCHUN" : "Unlit Torch",
		"STATUEWO" : "Glowing Statue",
		"CHICKEN_GRW" : "Egg Growing (1)",
		"CHICKEN_MAT" : "Chicken",
		"SPELLBOOK_HOE" : "Hand Of Evil",
		"SPELLBOOK_IMP" : "Create Imp",
		"SPELLBOOK_OBEY" : "Must Obey",
		"SPELLBOOK_SLAP" : "Slap",
		"SPELLBOOK_SOE" : "Sight of Evil",
		"SPELLBOOK_CTA" : "Call To Arms",
		"SPELLBOOK_CAVI" : "Cave-In",
		"SPELLBOOK_HEAL" : "Heal",
		"SPELLBOOK_HLDAUD" : "Hold Audience",
		"SPELLBOOK_LIGHTN" : "Lightning Strike",
		"SPELLBOOK_SPDC" : "Speed Monster",
		"SPELLBOOK_PROT" : "Protect Monster",
		"SPELLBOOK_CONCL" : "Conceal Monster",
		"CTA_ENSIGN" : "Cta Ensign",
		"ROOM_FLAG" : "Room Flag",
		"ANVIL" : "Anvil",
		"PRISON_BAR" : "Prison Bar",
		"CANDLESTCK" : "Candlestick",
		"GRAVE_STONE" : "Gravestone",
		"STATUE_HORNY" : "Aztec Statue",
		"TRAINING_POST" : "Training Post",
		"TORTURE_SPIKE" : "Torture Spike",
		"TEMPLE_SPANGLE" : "Temple Spangle",
		"POTION_PURPLE" : "Purple Potion",
		"POTION_BLUE" : "Blue Potion",
		"POTION_GREEN" : "Green Potion",
		"POWER_HAND" : "Power Hand",
		"POWER_HAND_GRAB" : "Power Hand Grab",
		"POWER_HAND_WHIP" : "Power Hand Whip",
		"CHICKEN_STB" : "Egg Stable (2)",
		"CHICKEN_WOB" : "Egg Wobbling (3)",
		"CHICKEN_CRK" : "Egg Cracking (4)",
		"GOLDL" : "Gold Pile (200)",
		"SPINNING_KEY" : "Spinning Key",
		"SPELLBOOK_DISEASE" : "Disease",
		"SPELLBOOK_CHKN" : "Chicken Spell",
		"SPELLBOOK_DWAL" : "Destroy Walls",
		"SPELLBOOK_TBMB" : "Time Bomb",
		"HERO_GATE" : "Hero Gate",
		"SPINNING_KEY2" : "Spinning Key 2",
		"ARMOUR" : "Armour Effect",
		"GOLD_HOARD_1" : "Treasury Hoard 1 (400)",
		"GOLD_HOARD_2" : "Treasury Hoard 2 (800)",
		"GOLD_HOARD_3" : "Treasury Hoard 3 (1200)",
		"GOLD_HOARD_4" : "Treasury Hoard 4 (1600)",
		"GOLD_HOARD_5" : "Treasury Hoard 5 (2000)",
		"LAIR_WIZRD" : "Wizard Lair",
		"LAIR_BARBR" : "Barbarian Lair",
		"LAIR_ARCHR" : "Archer Lair",
		"LAIR_MONK" : "Monk Lair",
		"LAIR_DWRFA" : "Dwarf Lair",
		"LAIR_KNGHT" : "Knight Lair",
		"LAIR_AVATR" : "Avatar Lair",
		"LAIR_TUNLR" : "Tunneller Lair",
		"LAIR_WITCH" : "Witch Lair",
		"LAIR_GIANT" : "Giant Lair",
		"LAIR_FAIRY" : "Fairy Lair",
		"LAIR_THIEF" : "Thief Lair",
		"LAIR_SAMUR" : "Samurai Lair",
		"LAIR_HORNY" : "Horned Reaper Lair",
		"LAIR_SKELT" : "Skeleton Lair",
		"LAIR_GOBLN" : "Troll Lair",
		"LAIR_DRAGN" : "Dragon Lair",
		"LAIR_DEMSP" : "Demon Spawn Lair",
		"LAIR_FLY" : "Fly Lair",
		"LAIR_DKMIS" : "Mistress Lair",
		"LAIR_SORCR" : "Warlock Lair",
		"LAIR_BILDM" : "Bile Demon Lair",
		"LAIR_IMP" : "Imp Lair",
		"LAIR_BUG" : "Beetle Lair",
		"LAIR_VAMP" : "Vampire Lair",
		"LAIR_SPIDR" : "Spider Lair",
		"LAIR_HLHND" : "Hell Hound Lair",
		"LAIR_GHOST" : "Ghost Lair",
		"LAIR_TENTC" : "Tentacle Lair",
		"SPECBOX_REVMAP" : "Reveal Map",
		"SPECBOX_RESURCT" : "Resurrect Creature",
		"SPECBOX_TRANSFR" : "Transfer Creature",
		"SPECBOX_STEALHR" : "Steal Hero",
		"SPECBOX_MULTPLY" : "Multiply Creatures",
		"SPECBOX_INCLEV" : "Increase Level",
		"SPECBOX_MKSAFE" : "Make Safe",
		"SPECBOX_HIDNWRL" : "Locate Hidden World",
		"WRKBOX_BOULDER" : "Box: Boulder Trap",
		"WRKBOX_ALARM" : "Box: Alarm Trap",
		"WRKBOX_POISONG" : "Box: Poison Gas Trap",
		"WRKBOX_LIGHTNG" : "Box: Lightning Trap",
		"WRKBOX_WRDOFPW" : "Box: Word of Power Trap",
		"WRKBOX_LAVA" : "Box: Lava Trap",
		"WRKBOX_DEMOLTN" : "Box: Demolition Trap",
		"WRKBOX_DUMMY1" : "Box: Dummy Trap 1",
		"WRKBOX_DUMMY2" : "Box: Dummy Trap 2",
		"WRKBOX_DUMMY3" : "Box: Dummy Trap 3",
		"WRKBOX_DUMMY4" : "Box: Dummy Trap 4",
		"WRKBOX_DUMMY5" : "Box: Dummy Trap 5",
		"WRKBOX_DUMMY6" : "Box: Dummy Trap 6",
		"WRKBOX_DUMMY7" : "Box: Dummy Trap 7",
		"WRKBOX_WOOD" : "Box: Wooden Door",
		"WRKBOX_BRACE" : "Box: Braced Door",
		"WRKBOX_STEEL" : "Box: Iron Door",
		"WRKBOX_MAGIC" : "Box: Magic Door",
		"WRKBOX_ITEM" : "Workshop Item",
		"WRKBOX_MIDAS" : "Box: Midas Door",
		"HEARTFLAME_RED" : "Red Heart Flame",
		"DISEASE" : "Disease Effect",
		"SCAVENGE_EYE" : "Scavenger Eye",
		"WORKSHOP_MACHINE" : "Workshop Machine",
		"GUARDFLAG_RED" : "Red Flag",
		"GUARDFLAG_BLUE" : "Blue Flag",
		"GUARDFLAG_GREEN" : "Green Flag",
		"GUARDFLAG_YELLOW" : "Yellow Flag",
		"FLAG_POST" : "Flagpole",
		"HEARTFLAME_BLUE" : "Blue Heart Flame",
		"HEARTFLAME_GREEN" : "Green Heart Flame",
		"HEARTFLAME_YELLOW" : "Yellow Heart Flame",
		"POWER_SIGHT" : "Casted Sight",
		"POWER_LIGHTNG" : "Casted Lightning",
		"TORTURER" : "Torturer",
		"LAIR_ORC" : "Orc Lair",
		"POWER_HAND_GOLD" : "Power Hand Gold",
		"SPINNCOIN" : "Spinning Coin",
		"STATUE2" : "Unlit Statue",
		"STATUE3" : "Statue 3",
		"STATUE4" : "Statue 4",
		"STATUE5" : "Statue 5",
		"SPECBOX_CUSTOM" : "Mysterious Box",
		"SPELLBOOK_ARMG" : "Armageddon Spell",
		"SPELLBOOK_POSS" : "Possess Spell",
		"GOLD_BAG" : "Gold Bag",
		"FERN" : "Fern",
		"FERN_BROWN" : "Brown Fern",
		"FERN_SMALL" : "Small Fern",
		"FERN_SMALL_BROWN" : "Small Brown Fern",
		"MUSHROOM_YELLOW" : "Yellow Mushroom",
		"MUSHROOM_GREEN" : "Green Mushroom",
		"MUSHROOM_RED" : "Red Mushroom",
		"LAIR_TMAGE" : "Time Mage Lair",
		"LAIR_DRUID" : "Druid Lair",
		"LILYPAD" : "Lilypad",
		"CATTAILS" : "Cattails",
		"BANNER" : "Banner",
		"LANTERN_PST" : "Lantern Post",
		"POTION_RED" : "Red Potion",
		"POTION_BROWN" : "Brown Potion",
		"POTION_WHITE" : "White Potion",
		"POTION_YELLOW" : "Yellow Potion",
		"ROCK_PILLAR" : "Rock Pillar",
		"ROCK" : "Rock",
		"LAVA_PILLAR" : "Lava Pillar",
		"LAVA_ROCK" : "Lava Rock",
		"ICE_PILLAR" : "Ice Pillar",
		"ICE_ROCK" : "Ice Rock",
		"WRKBOX_SECRET" : "Box: Secret Door",
		"GUARDFLAG_WHITE" : "White Flag",
		"HEARTFLAME_WHITE" : "White Heart Flame",
		"SPELLBOOK_RBND" : "Rebound",
		"GUARDFLAG_PURPLE" : "Purple Flag",
		"HEARTFLAME_PURPLE" : "Purple Heart Flame",
		"GUARDFLAG_BLACK" : "Black Flag",
		"HEARTFLAME_BLACK" : "Black Heart Flame",
		"GUARDFLAG_ORANGE" : "Orange Flag",
		"HEARTFLAME_ORANGE" : "Orange Heart Flame",
		"SPECBOX_HEALALL" : "Heal All",
		"SPECBOX_GETGOLD" : "Increase Gold",
		"SPECBOX_MKANGRY" : "Make Unhappy",
		"SPECBOX_MKUNSAFE" : "Weaken Walls",
		"SPELLBOOK_FRZ" : "Freeze",
		"SPELLBOOK_SLOW" : "Slow",
		"SPELLBOOK_FLGT" : "Flight",
		"SPELLBOOK_VSN" : "Vision",
		"SPELLBOOK_TUNLR" : "Create Tunneller"
	}
}

const slabs = {
"HARD": "Impenetrable Rock",
"GOLD": "Gold Seam",
"DIRT": "Earth",
"TORCH_DIRT": "Torch Earth",
"DRAPE_WALL": "Banner Wall",
"TORCH_WALL": "Torch Wall",
"TWINS_WALL": "Twins Wall",
"WOMAN_WALL": "Woman Wall",
"PAIR_WALL": "Pair Wall",
"DAMAGED_WALL": "Damaged Wall",
"PATH": "Dirt Path",
"PRETTY_PATH": "Claimed Area",
"LAVA": "Lava",
"WATER": "Water",
"ENTRANCE_ZONE": "Portal",
"ENTRANCE_WALL": "Portal Wall",
"TREASURY_AREA": "Treasure Room",
"TREASURY_WALL": "Treasure Room Wall",
"BOOK_SHELVES": "Library",
"LIBRARY_WALL": "Library Wall",
"PRISON_AREA": "Prison",
"PRISON_WALL": "Prison Wall",
"TORTURE_AREA": "Torture Chamber",
"TORTURE_WALL": "Torture Chamber Wall",
"TRAINING_AREA": "Training Room",
"TRAINING_WALL": "Training Room Wall",
"HEART_PEDESTAL": "Heart Room",
"HEART_WALL": "Heart Room Wall",
"WORKSHOP_AREA": "Workshop",
"WORKSHOP_WALL": "Workshop Wall",
"SCAVENGE_AREA": "Scavenger Room",
"SCAVENGER_WALL": "Scavenger Room Wall",
"TEMPLE_POOL": "Temple",
"TEMPLE_WALL": "Temple Wall",
"GRAVE_AREA": "Graveyard",
"GRAVE_WALL": "Graveyard Wall",
"HATCHERY": "Hatchery",
"HATCHERY_WALL": "Hatchery Wall",
"LAIR_AREA": "Lair",
"LAIR_WALL": "Lair Wall",
"BARRACK_AREA": "Barracks",
"BARRACK_WALL": "Barracks Wall",
"DOOR_WOODEN": "Wooden Door",
"DOOR_WOODEN2": "Wooden Door",
"DOOR_BRACE": "Braced Door",
"DOOR_BRACE2": "Braced Door",
"DOOR_STEEL": "Iron Door",
"DOOR_STEEL2": "Iron Door",
"DOOR_MAGIC": "Magic Door",
"DOOR_MAGIC2": "Magic Door",
"SLAB50": "Slab 50",
"BRIDGE_FRAME": "Bridge",
"GEMS": "Gems",
"GUARD_AREA": "Guard Post",
"PURPLE_PATH": "Purple Path",
"DOOR_SECRET" : "Secret Door",
"DOOR_SECRET2" : "Secret Door",
"DOOR_MIDAS" : "Midas Door",
"DOOR_MIDAS2" : "Midas Door",
"HARD_FLOOR" : "Bedrock",
"AUTOMATIC_WALL" : "Wall Automatic",
};
